//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminUser
    {
        [Required(ErrorMessage = "Không được bỏ trống tên")]
        [Display(Name = "Mã User")] //@Html.LabelFor
        public int ID { get; set; }
        //[Required(ErrorMessage ="Không được bỏ trống tên")]
        [Display(Name = "Tên Người Dùng")]
        public string NameUser { get; set; }
        [Display(Name = "Vị Trí")]
        public string RoleUser { get; set; }
        [Display(Name = "Nhập Mật Khẩu")]
        [Required(ErrorMessage = "Mật Khẩu không được trống")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }
        public string ConfirmPassord { get; set; }
    }
}