//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }
    
        public int IDCus { get; set; }
        [Display(Name ="Tên Người Dùng")]
        public string NameCus { get; set; }
        [Display(Name = "Số Điện Thoại")]
        public string PhoneCus { get; set; }
        [Display(Name = "Email")]
        public string EmailCus { get; set; }
        [Display(Name = "Mật Khẩu")]
        public string PassCus { get; set; }
        public string ConfirmPassCus { get; set; }
        [Display(Name = "Giới Tính")]
        public bool? GenderCus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
