//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ImagePro = "~/Content/image/add.png";
        }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        public int ProductID { get; set; }
        [Display(Name = "Tên Truyện")]
        public string NamePro { get; set; }
        [Display(Name = "Mô tả Truyện")]
        public string DecriptionPro { get; set; }
        [Display(Name = "Thể Loại")]
        public Nullable<int> Category { get; set; }
        [Display(Name = "Giá")]
        public Nullable<decimal> Price { get; set; }        
        public string ImagePro { get; set; }
        public Nullable<bool> Hot { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        [Display(Name ="Số lượng hàng còn lại")]
        public Nullable<int> Quantity { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
